dask:
  num_threads: 10
train:
  n_modes: [10]
  hankel: [False]
  num_trials: 0
  trial_size: 0.9
  time_units: "h"
  seed: 1234
reconstruct:
  reconstruct_start: "2019-11-01T00"
  reconstruct_end: "2019-12-31T18"
forecast:
  forecast_start: "2020-01-01T00"
  forecast_days: 45
ins:
  groundtruth: "input_data/era5_slice.zarr"
  svd: "input_data/svd.pkl"
  svd_hankel: "input_data/svd_hankel.pkl"
  scaler: "input_data/scaler.pkl"
outs:
  save_models: True
  deter_models_dir: "models/deterministic"
  deter_metrics_dir: "metrics/deterministic"
  proba_models_dir: "models/probabilistic"
  proba_metrics_dir: "metrics/probabilistic"
misc:
  pressure_level: 850
